server:
  port: 8092

spring:
  cloud:
    gateway:
      routes:
        - id: data-factory
          uri: http://localhost:8080
          predicates:
            - Path=/data-factory/{registry}/**
            - Method=GET
          filters:
            - name: ClientRegistrySetToken
              args:
                header: X-Access-Token
            - StripPrefix=2
        - id: bp-gateway
          uri: http://localhost:8081
          predicates:
            - Path=/bp-gateway/{registry}/**
            - Method=POST
          filters:
            - name: ClientRegistrySetToken
              args:
                header: X-Access-Token
            - StripPrefix=2
        - id: basicAuthRoute
          uri: http://localhost:8082
          predicates:
            - Path=/external/basicAuth/**
          filters:
            - name: BasicAuth
              args:
                username: username
                password: password
            - StripPrefix=2
        - id: public-api
          uri: http://localhost:8080
          predicates:
            - Path=/api/public/data-factory/**
            - Method=GET
          filters:
            - name: PublicApiAddToken
              args:
                header: X-Access-Token
            - StripPrefix=3

keycloak:
  url: http://localhost:8083
  public-api:
    realm: realm
    client-id: client-id
    client-secret: client-secret

vault:
  uri: http://localhost:8200
  token: myroot

registry:
  name: labs

logging:
  level:
    org.zalando.logbook: TRACE