spring:
  application:
    name: platform-gateway
  main:
    web-application-type: reactive
  zipkin:
    baseUrl: http://zipkin.istio-system.svc:9411
    sender:
      type: web
  sleuth:
    opentracing:
      enabled: true
    baggage:
      correlation-enabled: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
    loggers:
      enabled: true
    prometheus:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

platform:
  security:
    enabled: true
    whitelist:
      - /actuator/**

logbook:
  exclude:
    - /actuator/**

logging:
  level:
    org.springframework.boot.autoconfigure.web.reactive.error: DEBUG