global:
  disableRequestsLimits: false

name: platform-gateway

deployProfile: prod

version: 1.1.0

port: 8080

java:
  javaOpts: -Xms330m -Xmx330m -XX:+AlwaysPreTouch -XX:+UseG1GC

service:
  port: 8080

ingress:
  required: true
  site: platform-gateway

image:
  name: platform-gateway
  version: latest

monitoring:
  namespace: openshift-monitoring
  prometheusScrapePath: /actuator/prometheus
  jobLabel: app

probes:
  liveness:
    path: /actuator/health/liveness
  readiness:
    path: /actuator/health/readiness


restApi:
  externalRegistry:
    root:
      urlPattern: http://registry-rest-api-ext.{registry}.svc.cluster.local:8080
  public:
    root:
      urlPattern: http://registry-rest-api-public:8080
bpGateway:
  root:
    urlPattern: http://bp-webservice-gateway.{registry}.svc.cluster.local:8080

vault:
  url: http://hashicorp-vault:8200
  tokenSecret: central-vault-token

keycloak:
  realms:
    officer: officer-portal
    citizen: citizen-portal
    admin: admin
    externalSystem: external-system
  certificatesEndpoint: /protocol/openid-connect/certs
  publicApiClient:
    clientName: public-user
    secretName: keycloak-public-user-client-secret


############## EDP VARIABLES TEST VALUES ##############################
namespace: mock
cdPipelineName: pipe
cdPipelineStageName: dev
dnsWildcard: edp-epam.com
