global:
  container:
    requestsLimitsEnabled: true
  istio:
    sidecar:
      requestsLimitsEnabled: true
      resources:
        requests: {}
        limits: {}
  registry:
    platformGateway:
      container:
        envVars: {}
        resources:
          requests: {}
          limits: {}
      hpa:
        enabled: false
        minReplicas: 1
        maxReplicas: 3
      istio:
        sidecar:
          enabled: true
          resources:
            requests: {}
            limits: {}
      replicas: 1

name: platform-gateway

deployProfile: prod

version: 1.1.0

port: 8080

service:
  port: 8080

ingress:
  required: true
  site: platform-gateway

image:
  name: platform-gateway
  version: latest

monitoring:
  namespace: openshift-monitoring
  prometheusScrapePath: /actuator/prometheus
  jobLabel: app

probes:
  liveness:
    path: /actuator/health/liveness
  readiness:
    path: /actuator/health/readiness


restApi:
  externalRegistry:
    root:
      urlPattern: http://registry-rest-api-ext.{registry}.svc.cluster.local:8080
  public:
    root:
      urlPattern: http://registry-rest-api-public:8080
bpGateway:
  root:
    urlPattern: http://bp-webservice-gateway.{registry}.svc.cluster.local:8080

vault:
  url: http://hashicorp-vault:8200
  tokenSecret: central-vault-token

keycloak:
  realms:
    officer: officer-portal
    citizen: citizen-portal
    admin: admin
    externalSystem: external-system
  certificatesEndpoint: /protocol/openid-connect/certs
  publicApiClient:
    clientName: public-user
    secretName: keycloak-public-user-client-secret


############## EDP VARIABLES TEST VALUES ##############################
namespace: mock
cdPipelineName: pipe
cdPipelineStageName: dev
dnsWildcard: edp-epam.com
