{{- if .Values.global.registry.platformGateway.hpa.enabled }}
kind: HorizontalPodAutoscaler
apiVersion: {{ include "horizontalPodAutoscaler.apiVersion" . }}
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    relatedNamespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ .Values.name }}-deployment
    apiVersion: apps/v1
  minReplicas: {{ .Values.global.registry.platformGateway.hpa.minReplicas }}
  maxReplicas: {{ .Values.global.registry.platformGateway.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
{{- end }}
